name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Java version
      uses: actions/setup-java@v4
      with:
          distribution: "temurin"
          java-version: "8"

    - name: Build with Maven
      run: mvn clean install
    
    - name: Build container image
      uses: docker/build-push-action@v6
      with:
        context: src
        push: false
        file: Dockerfile
