name: workflow-2

on:
  workflow_call:
    inputs: 
        modules:
            required: true
            type: string
        variable:
            type: string



jobs:
  # build:
  #   environment: 
  #     name: develop
  #   runs-on: ubuntu-latest
  #   steps:
  #       - run: echo "This is from workflow2 from ${{inputs.modules}} with ${{secrets.ONE}} and variable ${{vars.NEW}}" 
  second_job:
    runs-on: ubuntu-latest
    environment: 
      name: develop
    steps:
        - run : echo "this is the second job of workflow2 ${{ env[format(inputs.variable)] }}"
        - run : echo "${{env}}"
#   call_workflow2:
#     uses: ./.github/workflows/workflow2.yml
#     with:
#       modules: workflow1